services:
  ibkr:
    build: .
    image: ibkr-rest-api
    container_name: ibkr
    ports:
      - "5056:5056" # app server
    volumes:
      - ./src:/app/webapp/src
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5056"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ibeam:
    image: voyz/ibeam
    container_name: ibeam
    env_file:
      - env.list
    ports:
      - "5055:5055"
    volumes:
      # - ./conf.yaml:/srv/clientportal.gw/root/conf.yaml
      - ./inputs/conf.yaml:/srv/inputs/conf.yaml
    network_mode: bridge # Required due to clientportal.gw IP whitelist
    restart: "no" # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    depends_on:
      ibkr:
        condition: service_healthy
